---
- name: Check Go version
  shell: go version | grep "{{ go.version }}"
  ignore_errors: True
  register: go_installed

- name: Remove old version of Go
  file:
    state: absent
    path: "{{ go.dir }}"
  become: yes
  when: go_installed is failed

- name: Download Go
  unarchive:
    src: "https://storage.googleapis.com/golang/go{{ go.version }}.linux-amd64.tar.gz"
    dest: /usr/local/
    remote_src: True
  become: yes
  when: go_installed is failed
