---
- name: Is Stack installed?
  shell: "hash stack 2>/dev/null"
  register: stack_installed
  ignore_errors: True

- name: Install Stack
  shell: "curl -sSL https://get.haskellstack.org/ | sh"
  become: yes
  when: stack_installed|failed

- name: Install Glassgow-Haskell Compiler and Friends
  command: "stack setup"

- name: Symlink Stack config
  file:
    src: "{{ playbook_dir }}/roles/proglang/files/stack.config.yaml"
    dest: "/home/{{ ansible_user }}/.stack/config.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
    force: yes

- name: Symlink .ghci
  file:
    src: "{{ playbook_dir }}/roles/proglang/files/.ghci"
    dest: "/home/{{ ansible_user }}/.ghci"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
    force: yes
