---

- name: Check for local pip installation
  command: which pip | grep {{ user_local }}
  register: pip_result

- name: Install pip locally for main system user
  command:  wget https://bootstrap.pypa.io/get-pip.py | python get-pip.py --user
  when: pip_result|failed

- name: Install virtualenv
  pip: name={{ item }}
       extra_args='--user'
  with_items: {{ pip_packages }}
