---
- name: Symlink in config files
  file:
    src: "{{ playbook_dir }}/roles/user/files/{{ item }}"
    dest: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/{{ item }}"
    owner: "{{ ansible_ssh_user|default(lookup('env', 'USER')) }}"
    group: "{{ ansible_ssh_user|default(lookup('env', 'USER')) }}"
    state: link
    force: yes
  with_items:
    - .bash_aliases
    - .bashrc
    - .vimrc
    - .bash_profile
    - .gitconfig
    - .inputrc
    - .tmux.conf
    - .dockerrc
