---
- name: Symlink in config files
  file:
    src: "{{ playbook_dir }}/roles/user/files/{{ item }}"
    dest: "/home/{{ ansible_user }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
    force: yes
  with_items:
    - .bash_aliases
    - .bashrc
    - .vimrc
    - .bash_profile
    - .gitconfig
    - .inputrc
    - .tmux.conf
    - .dockerrc

- name: Setup Git configuration
  git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: system
  with_dict:
    user.name: jad-b
    user.email: j.american.db@gmail.com
    user.signingkey: N/A
  become: yes
