# Setup Vim just the way I like it.

- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: Install vim plugins
  command: vim -E -s -c "source ~/.vimrc" +PluginInstall +qall
  ignore_errors: true
