---
- name: Grab Ubuntu distribution
  command: lsb_release -cs
  register: ubuntu_distro

- name: Grab kernel version
  command: uname -r
  register: linux_kernel

- name: Install linux kernel extras
  apt:
    name: "linux-image-extra-{{ linux_kernel.stdout }}"
    update_cache: yes

- name: Install Docker HTTPS Repo Pre-reqs
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - linux-image-extra-virtual

- name: Install Docker's GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Apt repositories
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_distro.stdout }} stable"
    mode: 0664

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes
    state: latest

- name: Add user to docker group
  user:
    append: yes
    groups: docker
    name: "{{ ansible_ssh_user|default(lookup('env', 'USER')) }}"
