---
- name: Install Docker HTTPS Repo Pre-reqs
  apt:
    name: 
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'software-properties-common'
    update_cache: yes

- name: Install Docker's GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Apt repositories
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    mode: 0664

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes
    state: latest

- name: Add user to docker group
  user:
    append: yes
    groups: docker
    name: "{{ ansible_user }}"

- name: Install docker-compose
  pip:
    name: docker-compose
    executable: pip3
    extra_args: "--user -U"
