---

- import_tasks: packages.yml
  tags: packages
  become: yes

  # - import_tasks: docker.yml
  #   tags: docker
  #   become: yes

- name: Create journal directory
  file:
    state: directory
    path: "/var/log/journal"
  become: yes

- name: Syncthing
  tags: syncthing
  become: yes
