---
- name: Add special Apt repos
  apt_repository:
    repo: "{{ item }}"
    mode: 0664
  with_items:
    - 'ppa:jonathonf/vim'
    - 'ppa:jonathonf/python-3.6'
    - 'ppa:teejee2008/ppa'

- name: Open up new Apt source list permissions
  shell: 'chmod og+r /etc/apt/sources.list.d/*.list'

- name: Install new packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ apps }}"

- name: dist-upgrade Apt packages
  apt:
    upgrade: dist
