---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install new packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ apps }}"

- name: Install network tools
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ network_apps }}"
