---
- name: Install Apt signing keys
  apt_key:
    url: "{{ item }}"
  with_items:
    - https://dl.google.com/linux/linux_signing_key.pub
    - https://download.opensuse.org/repositories/home:kozec/xUbuntu_16.04/Release.key
    - https://eddie.website/repository/keys/eddie_maintainer_gpg.key
    - https://syncthing.net/release-key.txt
    - https://updates.signal.org/desktop/apt/keys.asc
    - https://wire-app.wire.com/linux/releases.key
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Add special Apt repos
  apt_repository:
    repo: "{{ item }}"
    mode: 0664
  with_items:
    - 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    - 'deb [arch=amd64] https://wire-app.wire.com/linux/debian stable main'
    - 'deb http://eddie.website/repository/apt stable main'
    - 'deb https://apt.syncthing.net/ syncthing stable'
    - 'deb https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib'
    - 'ppa:neovim-ppa/stable'
    - 'ppa:nilarimogard/webupd8'
    - 'ppa:teejee2008/ppa'

- name: Install new packages
  apt:
    name: "{{ apps }}"
    state: latest
    update_cache: yes

- name: dist-upgrade Apt packages
  apt:
    upgrade: dist

- name: Install snaps
  snap:
    name:
      - slack
    classic: yes
