---
- name:  Add special Apt repos
  apt_repository:
    repo:  "{{ item }}"
  with_items:
    - 'ppa:jonathonf/vim'
    - 'ppa:ubuntu-mozilla-daily/firefox-aurora'

- name: Install new packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ apps }}"

- name: dist-upgrade Apt packages
  apt:
    upgrade: dist
