---
- name:  Add special Apt repos
  apt_repository:
    repo:  "{{ item }}"
    mode: 0664
  with_items:
    - 'ppa:jonathonf/vim'
    - 'ppa:ubuntu-mozilla-daily/firefox-aurora'

- name: Install new packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ apps }}"

- name: dist-upgrade Apt packages
  apt:
    upgrade: dist

- name: Remove unneeded packages
  apt:
    autoremove: yes
