---
apps:
  # Packages affecting the OS and foundational functionality
  - apt-file
  - anki
  - build-essential
  - compiz-plugins
  - compizconfig-settings-manager
  - git
  - google-chrome-stable
  - htop
  - jq
  - meld
  - neovim
  - network-manager-openvpn-gnome
  - powertop
  - redshift-gtk
  # - signal-desktop
  - software-properties-common
  - syncthing
  - syncthing-gtk
  - texlive-full
  - tiptop
  - tlp
  - tmux
  - tree
  - ubuntu-developer-tools-center
  - ubuntu-restricted-extras
  - unity-tweak-tool
  - virtualbox-6.0
  - ukuu
  - wire-desktop
  - xclip
  # Python system libraries
  - libbz2-dev
  - libc6-dev
  - libgdbm-dev
  - libncursesw5-dev
  - libreadline6-dev
  - libsqlite3-dev
  - libssl-dev
  - tk-dev
  - libncurses5-dev
  # Network Tools
  - iftop
  - netcat
  - nmap
  - traceroute
  - tshark

python:
  - python-dev
  - python-pip
  - python3-pip
  - python3-dev
