---
- hosts: miners
  sudo: yes
  vars:
    rstudio_deb: rstudio.deb
  tasks: 
  # sudo apt-key adv –keyserver keyserver.ubuntu.com –recv-keys E084DAB9
  - name: Add apt-key to ubuntu for CRAN
    apt_key: id=E084DAB9 keyserver=keyserver.ubuntu.com state=present
  # sudo add-apt-repository ‘deb http://star-www.st-andrews.ac.uk/cran/bin/linux/ubuntu trusty/’
  - name: Add the CRAN repo to our apt sources
    apt_repository: repo='deb http://star-www.st-andrews.ac.uk/cran/bin/linux/ubuntu trusty/' state=present

  # sudo apt-get update
  - name: Update apt cache
    apt: update_cache=yes

  # sudo apt-get install r-base r-base-dev
  - name: Install r packages
    apt: name={{ item }} state=latest
    with_items:
      - r-base
      - r-base-dev

  # Download and install RStudio
  # wget http://download1.rstudio.org/rstudio-0.98.1062-amd64.deb
  - name: Download RStudio
    get_url: url=http://download1.rstudio.org/rstudio-0.98.1062-amd64.deb dest=/tmp/{{rstudio_deb}}

  # sudo dpkg -i *.deb
  - name: Install RStudio
    apt: deb=/tmp/{{ rstudio_deb }}

  # rm *.deb
  - name: Remove rstudio .deb
    file: path=/tmp/{{ rstudio_deb }} state=absent
