---

- name: Add Apt keys by id & keyserver
  apt_key: id={{item.value.id}} keyserver=keyserver.ubuntu.com state=present
  with_dict: apt_repo_keys

- name: Add Apt keys by url
  apt_key: url={{item.value.url}} state=present
  with_dict: apt_repo_key_urls

- name: Add Apt repositories
  apt_repository: repo={{ item }} 
  with_items: apt_repos

- name: Update apt cache
  apt: update_cache=yes

- name: Install new packages
  apt: name={{ item }} state=latest
  with_items: apps

### The following require user interaction
# - name: Enable silverlight compatibility
#   shell: pipelight-plugin --enable silverlight && pipelight-plugin --enable widevine
# 
# - name: Download Dropbox
#   get_url: url=https://www.dropbox.com/download?plat=lnx.x86_64 dest=~/Downloads/dropbox_tar
# 
# - name: Unarchive the Dropbox deb
#   unarchive: src=~/Downloads/dropbox_tar dest=~/Downloads/dropbox/
# 
# - name: Run Dropbox daemon
#   shell: ./.dropbox-dist/dropboxd chdir=~/Downloads/dropbox/

